# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-03 15:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='slot',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
