# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-03 16:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0002_schedule_slot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='type',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
